/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redsaludtotal1;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import conectar.Conexion;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alexm
 */
public class chat extends javax.swing.JFrame {

    /**
     * Creates new form chat
     */
    String nombre;
    Connection conexion2;
    Conexion connect2=new Conexion();
    int i=2;
    public chat() {
          nombre=JOptionPane.showInputDialog("INTRODUCE TU NOMBRE");
           i=2;
        initComponents();
        hilo.start();
    }
    Thread hilo=new Thread(){
            @Override
            public void run()
            {
            for(i=2;i>1;i=i){
           conexion2=(Connection) connect2.getconection();
            PreparedStatement ps = null;
            ResultSet rs = null;
        try {
            ps=(PreparedStatement) conexion2.prepareStatement("select texto from chat");
            rs=ps.executeQuery();
              hilo.sleep(100);
              tt.setText(" ");
            while(rs.next())
            {
               tt.append("\n"+(String) rs.getObject(1));
            }
        }
            
       catch (SQLException ex) {
            Logger.getLogger(VisualizarProductos.class.getName()).log(Level.SEVERE, null, ex);
        }       catch (InterruptedException ex) {
                    Logger.getLogger(chat.class.getName()).log(Level.SEVERE, null, ex);
                }finally {try{ps.close();} catch (Exception e){}
            try{rs.close();} catch (Exception e){}
            try{conexion2.close();} catch (Exception e){}
            
        }
        System.out.println(i);
         }
               hilo.stop();
            }
            };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tt = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tt.setColumns(20);
        tt.setRows(5);
        jScrollPane1.setViewportView(tt);

        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("SALIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Conexion conect= new Conexion();
      Connection conexion=(Connection) conect.getconection();
     int d=0;
         
     PreparedStatement ps2=null;
         try {
             String text=nombre+": "+jTextField1.getText();
             ps2=(PreparedStatement) conexion.prepareStatement("insert into chat (texto) values(?)");
            ps2.setString(1, text);
            tt.append("\n"+text);
            ps2.executeUpdate();
             conexion.close();
             // TODO add your handling code here:
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "ERROR DE REGISTRO !\nREVISE QUE LOS CAMPOS ESTEN LLENADOS CORRECTAMENTE.");
         }finally {try{ps2.close();} catch (Exception e){}
            try{conexion.close();} catch (Exception e){} 
            
         }
         jTextField1.setText("");
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        tt.setText(" "); 
        Conexion connect=new Conexion();
            Connection conexion=(Connection) connect.getconection();
            PreparedStatement ps = null,st=null;
            ResultSet rs = null;
            
        try {
            ps=(PreparedStatement) conexion.prepareStatement("select texto from chat");
            rs=ps.executeQuery();
            st= (PreparedStatement) conexion.prepareStatement("DELETE FROM chat WHERE texto = ?");
            while(rs.next())
            {
               
               st.setString(1,rs.getString(1));
               st.executeUpdate(); 
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(VisualizarProductos.class.getName()).log(Level.SEVERE, null, ex);
        }finally {try{ps.close();} catch (Exception e){}
            try{rs.close();} catch (Exception e){}
            try{st.close();} catch (Exception e){}
            try{conexion.close();} catch (Exception e){}
        }
          i=0;
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea tt;
    // End of variables declaration//GEN-END:variables
}
