/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package redsaludtotal1;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.SwingUtilities;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Graphics;
/**
 *
 * @author alexm
 */
public class Crud1 extends javax.swing.JInternalFrame {

    /** Creates new form Crud1 */
    CardLayout vista;
    public Crud1() {
        initComponents();
        vista=(CardLayout) jPanel2.getLayout();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ingreso = new javax.swing.JToggleButton();
        actualizar = new javax.swing.JToggleButton();
        ventas = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        ver = new javax.swing.JToggleButton();
        ImageIcon icon=new ImageIcon(getClass().getResource("/imagenes/redsaludtotal.jpg"));
        Image image =icon.getImage();
        jPanel2 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g)
            {
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };

        principal.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));

        ingreso.setBackground(new java.awt.Color(255, 255, 0));
        ingreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/item1.png"))); // NOI18N
        ingreso.setText("INGRESAR");
        ingreso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ingreso.setOpaque(true);
        ingreso.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoActionPerformed(evt);
            }
        });

        actualizar.setBackground(new java.awt.Color(255, 255, 0));
        actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/item2.png"))); // NOI18N
        actualizar.setText("ACTUALIZAR");
        actualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        actualizar.setOpaque(true);
        actualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        ventas.setBackground(new java.awt.Color(255, 255, 0));
        ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/item4.png"))); // NOI18N
        ventas.setText("VENDER");
        ventas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ventas.setOpaque(true);
        ventas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasActionPerformed(evt);
            }
        });

        jToggleButton3.setBackground(new java.awt.Color(255, 51, 51));
        jToggleButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton3.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/item5.png"))); // NOI18N
        jToggleButton3.setText("SALIR");
        jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton3.setOpaque(true);
        jToggleButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        ver.setBackground(new java.awt.Color(255, 255, 0));
        ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/item3.png"))); // NOI18N
        ver.setText("VISUALIZAR");
        ver.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ver.setOpaque(true);
        ver.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 125, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addComponent(ver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ventas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ingreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        jPanel2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoActionPerformed
        if (ingreso.isSelected())
        {
            jPanel2.add(new IngresarProductos(),"abc");
            vista.show(jPanel2, "abc");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            ingreso.setBackground(Color.white);
            actualizar.setEnabled(false);
            ver.setEnabled(false);
            ventas.setEnabled(false);
        }else if(ingreso.isSelected()==false)
        {
            jPanel2.removeAll();
            jPanel2.repaint();
            ingreso.setBackground(Color.yellow);
            actualizar.setEnabled(true);
            ver.setEnabled(true);
            ventas.setEnabled(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresoActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        if (actualizar.isSelected())
        {
            jPanel2.add(new ModificarProductos(),"act");
            vista.show(jPanel2, "act");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            actualizar.setBackground(Color.white);
            ingreso.setEnabled(false);
            ver.setEnabled(false);
            ventas.setEnabled(false);
        }else if(actualizar.isSelected()==false)
        {
            actualizar.setBackground(Color.yellow);
            jPanel2.removeAll();
            jPanel2.repaint();
            ingreso.setEnabled(true);
            ver.setEnabled(true);
            ventas.setEnabled(true);
        }          // TODO add your handling code here:
    }//GEN-LAST:event_actualizarActionPerformed

    private void ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasActionPerformed
        if (ventas.isSelected())
        {
            jPanel2.add(new Ventas(),"vender");
            vista.show(jPanel2, "vender");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            ventas.setBackground(Color.white);
            ingreso.setEnabled(false);
            actualizar.setEnabled(false);
            ver.setEnabled(false);
        }else if(ventas.isSelected()==false)
        {
            jPanel2.removeAll();
            jPanel2.repaint();
            ventas.setBackground(Color.yellow);
            ingreso.setEnabled(true);
            actualizar.setEnabled(true);
            ver.setEnabled(true);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_ventasActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        if (ver.isSelected())
        {
            jPanel2.add(new VisualizarProductos(),"visual");
            vista.show(jPanel2, "visual");
            SwingUtilities.updateComponentTreeUI(this);
            this.repaint();
            ver.setBackground(Color.white);
            ingreso.setEnabled(false);
            actualizar.setEnabled(false);
            ventas.setEnabled(false);
        }else if(ver.isSelected()==false)
        {
            jPanel2.removeAll();
            jPanel2.repaint();
            ver.setBackground(Color.yellow);
            ingreso.setEnabled(true);
            actualizar.setEnabled(true);
            ventas.setEnabled(true);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_verActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton actualizar;
    private javax.swing.JToggleButton ingreso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JPanel principal;
    private javax.swing.JToggleButton ventas;
    private javax.swing.JToggleButton ver;
    // End of variables declaration//GEN-END:variables

}
