/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redsaludtotal1;

import ingresarImagen.PintarImagenBd;
import ingresarImagen.PintarImagen;
import conectar.Conexion;
import com.mysql.jdbc.Blob;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static redsaludtotal1.InterfazIngreso.cargo;
import static redsaludtotal1.InterfazIngreso.id_user;
        
/**
 *
 * @author alexm
 */
public class ModificarProductos extends javax.swing.JPanel {

    /**
     * Creates new form ModificarProductos
     
     */
    String a,b;
    PreparedStatement ps,ps2;
    ResultSet rs,rs2;
    Image fotito;
     File archivo;
     java.sql.Date date2;
     int cantidad,id;
    public ModificarProductos() {
        initComponents();
        this.a = id_user;
        this.b = cargo;
        jButton2.setEnabled(false);
        cantidadP.setEnabled(false);
        cantidadP1.setEnabled(false);
    }
 
public void obtenerDate() 
{
   date2=new java.sql.Date(fechaP.getDate().getTime());
    System.out.println(date2);
}
public void comparar()
    {
        if(b.equalsIgnoreCase("Administrador")){
            cantidadP1.setEnabled(true);
        }else{
            cantidadP1.setEnabled(false);
        JOptionPane.showMessageDialog(null,"UD NO TIENE EL PRIVILEGIO DE RESTAR PRODUCTOS");}
    }
public void limpiar()
{
    nombreP.setText(" ");
    precioP.setText(" ");
    fechaP.setDate(null);
    cantidadP.setValue(0);
    textoP.setText(" ");
    imagenP.removeAll();
    imagenP.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaP = new com.toedter.calendar.JDateChooser();
        nombreP = new javax.swing.JTextField();
        precioP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoP = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cantidadP = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        imagenP = new javax.swing.JPanel();
        code = new javax.swing.JTextField();
        activar = new javax.swing.JCheckBox();
        jToggleButton1 = new javax.swing.JToggleButton();
        cantidadP1 = new javax.swing.JSpinner();
        uno = new javax.swing.JCheckBox();
        dos = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("NOMBRE :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("PRECIO :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("FECHA CADUCIDAD :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("DESCRIPCION:");

        nombreP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombrePKeyTyped(evt);
            }
        });

        textoP.setColumns(20);
        textoP.setRows(5);
        textoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textoPKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(textoP);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("*maximo 90 caracteres*");

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("MODIFICAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cantidadP.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("NUEVA IMAGEN :");

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("BUSCAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        imagenP.setBackground(new java.awt.Color(0, 0, 0));
        imagenP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));

        javax.swing.GroupLayout imagenPLayout = new javax.swing.GroupLayout(imagenP);
        imagenP.setLayout(imagenPLayout);
        imagenPLayout.setHorizontalGroup(
            imagenPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );
        imagenPLayout.setVerticalGroup(
            imagenPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        code.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        code.setText("1");
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });

        activar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        activar.setForeground(new java.awt.Color(255, 255, 255));
        activar.setText("SI");
        activar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activarActionPerformed(evt);
            }
        });

        jToggleButton1.setText("BUSCAR");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        cantidadP1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        uno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        uno.setForeground(new java.awt.Color(255, 255, 255));
        uno.setText("AÑADIR");
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        dos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dos.setForeground(new java.awt.Color(255, 255, 255));
        dos.setText("RESTAR");
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(fechaP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precioP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(activar)
                                        .addGap(39, 39, 39))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(uno)
                                            .addComponent(cantidadP, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(dos)
                                        .addComponent(cantidadP1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 222, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagenP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton1))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreP)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(precioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(fechaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(uno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cantidadP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantidadP1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(activar)
                                    .addComponent(jButton2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dos)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagenP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)))
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser buscar =new JFileChooser();
        buscar.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        FileNameExtensionFilter filtro =new FileNameExtensionFilter("*.jpg", "jpg");
        buscar.setFileFilter(filtro);
        int seleccion = buscar.showOpenDialog(this);
        if(seleccion==JFileChooser.APPROVE_OPTION)
        {   archivo =buscar.getSelectedFile();
            String ruta=archivo.getAbsolutePath();
            int ancho=imagenP.getWidth();
            int alto=imagenP.getHeight();
            PintarImagen foto=new PintarImagen(ancho,alto,ruta);
            imagenP.removeAll();
            imagenP.repaint();
            imagenP.add(foto);
            imagenP.repaint();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 int resultado=0,resultado2=0;
    if(!nombreP.getText().isEmpty()&&(uno.isSelected()==true||dos.isSelected()==true)&&!precioP.getText().isEmpty()&&!textoP.getText().isEmpty()&&(cantidadP.isEnabled()==true||cantidadP1.isEnabled()==true)&&fechaP!=null)
     {
     Conexion conect= new Conexion();
     obtenerDate();
     PreparedStatement ps2=null,ps=null;
     Connection conexion=(Connection) conect.getconection();
         try {
             ps2=(PreparedStatement) conexion.prepareStatement("update producto set nombre=?,precio=?,caducidad=?,descripcion=?,cantidad=? where id_producto=?");
           
            if(cantidadP.isEnabled()==true&&cantidadP1.isEnabled()==false)
            {
                int cantidadd=cantidad+(int)cantidadP.getValue();
                ps2.setString(1, nombreP.getText());
                ps2.setString(2, precioP.getText());
                ps2.setDate(3, date2);
                ps2.setString(4, textoP.getText());
                if(cantidadd>=0){
                ps2.setInt(5,cantidadd);   
                }else{
                    JOptionPane.showMessageDialog(null,"EL STOCK DEL PRODUCTO NO PUEDE SER MENOR A 0");
                }
                ps2.setInt(6, Integer.parseInt(code.getText()));
                resultado=ps2.executeUpdate();
            }else if(cantidadP.isEnabled()==false&&cantidadP1.isEnabled()==true){
                int cantidadd=cantidad-(int)cantidadP1.getValue();
                ps2.setString(1, nombreP.getText());
                ps2.setString(2, precioP.getText());
                ps2.setDate(3, date2);
                ps2.setString(4, textoP.getText());
                if(cantidadd>=0){
                 ps2.setInt(5,cantidadd);   
                }else{
                    JOptionPane.showMessageDialog(null,"EL STOCK DEL PRODUCTO NO PUEDE SER MENOR A 0");
                }
                ps2.setInt(6, Integer.parseInt(code.getText()));
                resultado=ps2.executeUpdate();
            }
            System.out.println(id);
            if(archivo!=null&&activar.isEnabled()){
                FileInputStream archivoimg=new FileInputStream(archivo); 
                ps=(PreparedStatement) conexion.prepareStatement("update imagen_producto set imagen=? where id_producto=?");
                ps.setBinaryStream(1, archivoimg,(int) archivo.length());
                ps.setInt(2, id);
                ps.executeUpdate();
            }
            JOptionPane.showMessageDialog(null, "MODIFICADO CORRECTAMENTE");
         } catch (FileNotFoundException ex) {
             System.err.println("ERROR");
         } catch (SQLException ex) {
             System.err.println("ERROR ");
         }finally {try{ps2.close();} catch (Exception e){}
            try{conexion.close();} catch (Exception e){}
         }
          }else {System.out.println("hola");JOptionPane.showMessageDialog(null, "ERROR DE REGISTRO !\nREVISE QUE LOS CAMPOS ESTEN LLENADOS CORRECTAMENTE.");}
        
             // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void activarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activarActionPerformed
        if(activar.isSelected())
        jButton2.setEnabled(true);
        else  jButton2.setEnabled(false);       // TODO add your handling code here:
    }//GEN-LAST:event_activarActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if(jToggleButton1.isSelected()==false)
        {
        imagenP.removeAll();
        imagenP.repaint();
        limpiar();
        }else
        {
        Conexion conect= new Conexion();
      Connection conexion=(Connection) conect.getconection();
        try {
            ps=(PreparedStatement) conexion.prepareStatement("select * from producto where id_producto=?");
            ps.setString(1,code.getText());
            rs=ps.executeQuery();      
            if(rs.next())
            {      
                nombreP.setText(rs.getString("nombre"));
                precioP.setText(String.valueOf(rs.getDouble("precio")));
                fechaP.setDate(rs.getDate("caducidad"));
                textoP.setText(rs.getString("descripcion"));
                cantidadP.setValue(rs.getInt("cantidad"));
                cantidad=rs.getInt("cantidad");
                id=rs.getInt("id_producto");
                ps2=(PreparedStatement) conexion.prepareStatement("select * from imagen_producto where id_producto=?");
                ps2.setInt(1,rs.getInt("id_producto"));
                rs2=ps2.executeQuery();
                Blob imagen=null;       
                if(rs2.next())
                {     
                 try {
                       Blob imagenbd=(Blob) rs2.getBlob("imagen");
                       fotito=javax.imageio.ImageIO.read(imagenbd.getBinaryStream());
                        PintarImagenBd im=new PintarImagenBd(imagenP.getWidth(), imagenP.getHeight(), fotito);
                        imagenP.add(im);
                        imagenP.repaint();
                    } catch (IOException ex) {
                        Logger.getLogger(ModificarProductos.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                }
            }else {JOptionPane.showMessageDialog(null, "PRODUCTO NO EXISTE");}
             
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(ModificarProductos.class.getName()).log(Level.SEVERE, null, ex);
        }finally {try{ps.close();} catch (Exception e){}
            try{rs.close();} catch (Exception e){}
             try{ps2.close();} catch (Exception e){}
            try{rs2.close();} catch (Exception e){}
            try{conexion.close();} catch (Exception e){}   
            
        } 
        }// TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void nombrePKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombrePKeyTyped
   char caracter=evt.getKeyChar();
        if(Character.isLowerCase(caracter))
        {
        evt.setKeyChar(Character.toUpperCase(caracter));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePKeyTyped

    private void textoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoPKeyTyped
   char caracter=evt.getKeyChar();
        if(Character.isLowerCase(caracter))
        {
        evt.setKeyChar(Character.toUpperCase(caracter));
        }        // TODO add your handling code here:
    }//GEN-LAST:event_textoPKeyTyped

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
    if(uno.isSelected())
    {
        cantidadP.setEnabled(true);
    }else cantidadP.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_unoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
    if(dos.isSelected())
    {
        comparar();
    }else cantidadP1.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_dosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activar;
    private javax.swing.JSpinner cantidadP;
    private javax.swing.JSpinner cantidadP1;
    private javax.swing.JTextField code;
    private javax.swing.JCheckBox dos;
    private com.toedter.calendar.JDateChooser fechaP;
    private javax.swing.JPanel imagenP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nombreP;
    private javax.swing.JTextField precioP;
    private javax.swing.JTextArea textoP;
    private javax.swing.JCheckBox uno;
    // End of variables declaration//GEN-END:variables
}
