/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redsaludtotal1;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import conectar.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexm
 */
public class Ventas extends javax.swing.JPanel {
DefaultTableModel modelo2 =new DefaultTableModel(){
    @Override
    public boolean isCellEditable(int row, int column) {
        if(column==5)
        {
            return true;
        }else return false;
//To change body of generated methods, choose Tools | Templates.
    }
    
};
    /**
     * Creates new form Ventas
     */
int contador=0;
    public Ventas() {
        initComponents();
        modelotabla();
    }
    public void comparar(String codigo)
    {  contador=0;
        int x=modelo2.getRowCount();
        for(int i=0;i<x;i++)
        {
            if(codigo.equalsIgnoreCase((String) modelo2.getValueAt(i, 0)))
            {
                ++contador;
            }
        }
    }
     public void compararnombre(String nombre)
    {  contador=0;
        int x=modelo2.getRowCount();
        for(int i=0;i<x;i++)
        {
            if(nombre.equalsIgnoreCase((String) modelo2.getValueAt(i, 1)))
            {
                ++contador;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void modelotabla()
    {
            tablita.setModel(modelo2);
            modelo2.addColumn("CODIGO");
            modelo2.addColumn("NOMBRE");
            modelo2.addColumn("PRECIO");
            modelo2.addColumn("STOCK");
            modelo2.addColumn("CANTIDAD COMPRA");
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        nom = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(255, 153, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("*ESCRIBA EL CODIGO O NOBRE DEL PRODUCTO QUE DESEA COMPRAR*");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PRODUCTOS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CANTIDAD");

        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "NOMBRE", "PRECIO", "STOCK", "CANTIDAD COMPRA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablita);

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("VENDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("INGRESAR POR NOMBRE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("INGRESAR POR CODIGO");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("ELIMINAR ITEM");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("2.- PRESIONE EL BOTON ELIMINAR");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("1.- SELECCIONE EL ITEM EN LA TABLA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2)
                .addGap(35, 35, 35))
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton5)))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         Conexion conect= new Conexion();
     
            PreparedStatement ps = null;
            ResultSet rs = null;  
            Connection conexion=(Connection) conect.getconection();
        try {
            int cantidad;
            ps=(PreparedStatement) conexion.prepareStatement("select * from producto where id_producto=?");
            ps.setString(1,code.getText());
            rs=ps.executeQuery();
            comparar(code.getText());
            if(contador<=0)
            {
            while(rs.next())
            {
                cantidad=Integer.parseInt(rs.getString(5));
                    if(cantidad>=(int)jSpinner1.getValue()&&(int)jSpinner1.getValue()!=0)
                    {
                Object fila[]=new Object[5];
                    fila[0]=rs.getObject(1);
                     fila[1]=rs.getObject(2);
                      fila[2]=rs.getObject(3);
                       fila[3]=rs.getObject(5);
                        fila[4]=jSpinner1.getValue();
                modelo2.addRow(fila);
                    }else JOptionPane.showMessageDialog(null,"EL STOCK DEL PRODUCTO \nES MENOR A LA CANTIDAD DE COMPRA \nO SU COMPRA ES NULA");
            }
            }else JOptionPane.showMessageDialog(null,"PRODUCTO YA INGRESADO EN LA TABLA");
            // TODO add your handling code here:
            } catch (SQLException ex) {
            Logger.getLogger(ModificarProductos.class.getName()).log(Level.SEVERE, null, ex);
        }finally {try{ps.close();} catch (Exception e){}
            try{rs.close();} catch (Exception e){}
            try{conexion.close();} catch (Exception e){}
            
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     Conexion conect= new Conexion();
            PreparedStatement ps = null;
            ResultSet rs = null;  
            Connection conexion=(Connection) conect.getconection();
        try {
            int cantidad;
            ps=(PreparedStatement) conexion.prepareStatement("select * from producto where nombre=?");
            ps.setString(1,nom.getText());
            rs=ps.executeQuery();
            compararnombre(nom.getText());
            if(contador<=0)
            {
            while(rs.next())
            {
                
                    cantidad=Integer.parseInt(rs.getString(5));
                    if(cantidad>=(int)jSpinner1.getValue()&&(int)jSpinner1.getValue()!=0)
                    {
                Object fila[]=new Object[5];
                    fila[0]=rs.getObject(1);
                     fila[1]=rs.getObject(2);
                      fila[2]=rs.getObject(3);
                       fila[3]=rs.getObject(5);
                        fila[4]=jSpinner1.getValue();
                modelo2.addRow(fila);
                    }else JOptionPane.showMessageDialog(null,"EL STOCK DEL PRODUCTO \nES MENOR A LA CANTIDAD DE COMPRA \nO SU COMPRA ES NULA");
            
            }
            }else JOptionPane.showMessageDialog(null,"PRODUCTO YA INGRESADO EN LA TABLA");
            // TODO add your handling code here:
            } catch (SQLException ex) {
            Logger.getLogger(ModificarProductos.class.getName()).log(Level.SEVERE, null, ex);
        }finally {try{ps.close();} catch (Exception e){}
            try{rs.close();} catch (Exception e){}
            try{conexion.close();} catch (Exception e){}
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int fila=tablita.getRowCount();
      int resultado = 0;
        Conexion conect= new Conexion();
     PreparedStatement ps2=null;     
     Connection conexion=(Connection) conect.getconection();
         try {
                 for(int i=fila-1;i>=0;i--)
            {
                int x=Integer.parseInt(String.valueOf(modelo2.getValueAt(i, 3)) ) ;
                int y=Integer.parseInt(String.valueOf(modelo2.getValueAt(i, 4)) ) ;
                if(x>=y)
                {
             ps2=(PreparedStatement) conexion.prepareStatement("update producto set cantidad=? where id_producto=?");
            int cantidadn=Integer.parseInt(String.valueOf(modelo2.getValueAt(i, 3)) )-Integer.parseInt(String.valueOf(modelo2.getValueAt(i, 4)) );
             ps2.setInt(1, cantidadn);
             ps2.setInt(2, (int) modelo2.getValueAt(i, 0));
             resultado=ps2.executeUpdate();
                }else {JOptionPane.showMessageDialog(null,"ITEM *"+modelo2.getValueAt(i, 1)+"*"+" NO SE PUDO MODIFICAR\nREVISE QUE EL STOCK SEA MAYOR A LA COMPRA\n"
                        + "COMPRA NO REALIZADA");break; }
                
             }
                 for(int i=fila-1;i>=0;i--)
                    {
                     modelo2.removeRow(i);
                    }
            JOptionPane.showMessageDialog(null,"PRODUCTOS VENDIDOS CORRECTAMENTE");
             // TODO add your handling code here:
         } catch (SQLException ex) {
             Logger.getLogger(IngresarProductos.class.getName()).log(Level.SEVERE, null, ex);
         }finally {try{ps2.close();} catch (Exception e){}
            try{conexion.close();} catch (Exception e){}
            
         }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    int fila=tablita.getSelectedRow();
    if(fila>=0)
    {
        modelo2.removeRow(fila);
    }else JOptionPane.showMessageDialog(null,"SELECCIONE UN ITEM");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField nom;
    private javax.swing.JTable tablita;
    // End of variables declaration//GEN-END:variables
}
