/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package redsaludtotal1;

import ingresarImagen.PintarImagenBd;
import conectar.Conexion;
import com.mysql.jdbc.Blob;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Image;
import java.io.IOException;
import javax.swing.ImageIcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author alexm
 */
public class VisualizarProductos extends javax.swing.JPanel {

    /**
     * Creates new form VisualizarProductos
     */
    PreparedStatement ps=null;
    ResultSet rs=null;
    Image fotito;
    public VisualizarProductos() {
        initComponents();
      
    }
    public void llenarTabla1()
    {     DefaultTableModel modelo =new DefaultTableModel();
            tabla1.setModel(modelo);
            Conexion connect=new Conexion();
            Connection conexion=(Connection) connect.getconection();
        try {
            ps=(PreparedStatement) conexion.prepareStatement("select nombre,precio,caducidad,descripcion,cantidad,id_producto from producto");
            rs=ps.executeQuery();
            modelo.addColumn("PRODUCTO");
            modelo.addColumn("PRECIO");
            modelo.addColumn("CADUCIDAD");
            modelo.addColumn("DESCRIPCION");
            modelo.addColumn("CANTIDAD");
               modelo.addColumn("CODIGO");
            while(rs.next())
            {
                Object fila[]=new Object[6];
                for(int i=0;i<6;i++)
                {
                    fila[i]=rs.getObject(i+1);
                    
                }
                modelo.addRow(fila);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(VisualizarProductos.class.getName()).log(Level.SEVERE, null, ex);
        }finally {try{ps.close();} catch (Exception e){}
            try{rs.close();} catch (Exception e){}
            try{conexion.close();} catch (Exception e){}
            
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nombreP = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        imagenP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCTO", "PRECIO", "CADUCIDAD", "DESCRIPCION", "CANTIDAD", "CODIGO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 490, 210));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("NOMBRE DEL PRODUCTO :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 193, -1));

        nombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePActionPerformed(evt);
            }
        });
        add(nombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 152, -1));

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("BUSCAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCTO", "PRECIO", "CADUCIDAD", "DESCRIPCION", "CANTIDAD", "CODIGO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 490, 55));

        imagenP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));

        javax.swing.GroupLayout imagenPLayout = new javax.swing.GroupLayout(imagenP);
        imagenP.setLayout(imagenPLayout);
        imagenPLayout.setHorizontalGroup(
            imagenPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        imagenPLayout.setVerticalGroup(
            imagenPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        add(imagenP, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, 230));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PRODUCTO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 110, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IMAGEN ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 80, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DEL");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 80, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("VISUALIZAR TODOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 490, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        imagenP.removeAll();
        imagenP.repaint();
        Conexion conect= new Conexion();
      DefaultTableModel modelo2 =new DefaultTableModel();
            tabla2.setModel(modelo2);
            Connection conexion=(Connection) conect.getconection();
        try {
            int id=0;
            ps=(PreparedStatement) conexion.prepareStatement("select * from producto where nombre=?");
            ps.setString(1,nombreP.getText());
            rs=ps.executeQuery();
             Blob imagen=null; 
                modelo2.addColumn("PRODUCTO");
            modelo2.addColumn("PRECIO");
            modelo2.addColumn("CADUCIDAD");
            modelo2.addColumn("DESCRIPCION");
            modelo2.addColumn("CANTIDAD");
               modelo2.addColumn("CODIGO");
            while(rs.next())
            {
                id=rs.getInt("id_producto");
                   Object fila[]=new Object[6];
                    fila[0]=rs.getObject(2);
                      fila[1]=rs.getObject(3);
                        fila[2]=rs.getObject(4);
                          fila[3]=rs.getObject(6);
                            fila[4]=rs.getObject(5);
                              fila[5]=rs.getObject(1);
                                modelo2.addRow(fila);
               
            }
            rs=null;
            ps=null;
            ps=(PreparedStatement) conexion.prepareStatement("select * from imagen_producto where id_producto=?");
            ps.setInt(1,id);
            rs=ps.executeQuery();
            while(rs.next()){
                   Blob imagenbd=(Blob) rs.getBlob("imagen");
                   fotito=javax.imageio.ImageIO.read(imagenbd.getBinaryStream());
                    PintarImagenBd im=new PintarImagenBd(imagenP.getWidth(), imagenP.getHeight(), fotito);
                    imagenP.add(im);
                    imagenP.repaint();
             }
            if(modelo2.getRowCount()==0)
            {
                {JOptionPane.showMessageDialog(null, "PRODUCTO NO EXISTE");}
            }
            
            // TODO add your handling code here:
            }catch (IOException ex) {
                    Logger.getLogger(ModificarProductos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
            Logger.getLogger(ModificarProductos.class.getName()).log(Level.SEVERE, null, ex);
        }finally {try{ps.close();} catch (Exception e){}
            try{rs.close();} catch (Exception e){}
            try{conexion.close();} catch (Exception e){}
            
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
llenarTabla1();           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel imagenP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nombreP;
    private javax.swing.JTable tabla1;
    private javax.swing.JTable tabla2;
    // End of variables declaration//GEN-END:variables
}
